# Generated by Django 4.0.1 on 2022-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=30, verbose_name='Услуги')),
                ('price', models.IntegerField(verbose_name='Цены')),
            ],
            options={
                'verbose_name': 'Цена на услугу',
                'verbose_name_plural': 'Цены на услуги',
            },
        ),
    ]
