# Generated by Django 4.0.1 on 2022-05-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_pricelist_options_alter_pricelist_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='services',
            new_name='title',
        ),
    ]
