# Generated by Django 4.0.1 on 2022-05-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Производитель')),
                ('slug', models.SlugField(default=models.CharField(db_index=True, max_length=150, verbose_name='Производитель'), max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Категория')),
                ('slug', models.SlugField(default=models.CharField(db_index=True, max_length=150, verbose_name='Категория'), max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('on_sale', models.BooleanField(default=True, verbose_name='В продаже')),
                ('units_price', models.IntegerField(verbose_name='Цена')),
                ('units_in_stock', models.IntegerField(verbose_name='Остаток')),
                ('article', models.CharField(max_length=20, null=True, verbose_name='Артикул')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productcategory', verbose_name='Категория')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Вторичное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Вторичное фото товара',
                'verbose_name_plural': 'Вторичные фото товара',
                'ordering': ['product_id', 'id'],
            },
        ),
    ]
