# Generated by Django 4.0.1 on 2022-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='slug',
            field=models.SlugField(default=models.CharField(db_index=True, max_length=150, verbose_name='Производитель'), max_length=70, unique=True, verbose_name='SLUG производителя'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=models.CharField(db_index=True, max_length=150, verbose_name='Категория'), max_length=70, unique=True, verbose_name='SLUG продукта'),
        ),
    ]
