# Generated by Django 4.0.1 on 2022-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_producer_slug_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=70, unique=True, verbose_name='SLUG категории'),
        ),
    ]
